### ISSUE TITLE
Backtesting raises an exception if `go_long` or `go_short` uses a `qty` of zero

### ISSUE THREAD

**Issue by poe28** [jesse-ai/jesse#287]
**Describe the bug**
A clear and concise description of what the bug is. Include the whole error message / traceback.
Backtesting raises an exception if `go_long` or `go_short` uses a `qty` of zero:
```
Uncaught Exception: InvalidStrategy: qty cannot be 0
```
**To Reproduce**
1. Include your routes.py, config.py (make sure to remove personal information) and if possible your strategy code (if you want to keep it private - contact us on Discord directly).
Use strategy [RSI2](https://github.com/jesse-ai/example-strategies/tree/master/RSI2) with the following route:  
```
routes = [('Bitfinex', 'BTC-EUR', '5m', 'RSI2'),]
```
2. Explain the steps you do that lead to the error
```
jesse backtest 2021-04-01 2021-07-31
```
(also other date ranges will lead to the same result)
**Expected behavior**
I think it should not be the burden of the strategy to test in its `should_long` and `should_short` methods to test whether later on `qty` would be zero. It is more convenient if the strategy handling allows a `qty` of zero and just ignores it.
**Screenshots**

**Enviroment (please complete the following information):**
 - OS: [e.g. iOS, Windows, Ubuntu]
 Ubuntu
 - Version [use `pip show jesse`] 
Version: 0.29.3

**Additional context**

**Comment by cryptocoinserver** [comment]
Thank you for your feedback. Not sure it's a good idea to make that default behavior. As this Exception is valuable information about the strategy entry / position size logic. Especially for beginners that do experiments. Just ignoring the entry without feedback to the user might even seem like a bug. The user maybe wouldn't even be aware that (valuable) entry signals are "missed" because of an position size calculation that leads to very low qty + rounding / zero qty.

More advanced users like you can use a filter or as you suggested an additional condition in the entry signal to skip entries where the in the strategy calculated qty is 0 (or near zero + rounding).

**Comment by poe28** [comment]
OK, but I have just used the RSI2 strategy from the `example-strategies` repository. Shouldn't such strategies be role models how to write a strategy? Then, this strategy should contain a 0 qty check. (Indeed, it seems that any strategy should, because all what happens here is that you run out of capital, and then a 0 qty situation necessarily arises, while you would still like to see the backtest data explaining why you run out of capital, and not just an exception.) 
By the way, I could reproduce the error with 1h candles (which makes more sense than 5m) and a longer period:
```
jesse backtest 2017-12-01 2021-11-17
```

**Comment by cryptocoinserver** [comment]
You are right about the example-strategies. I added a warning there for now until we find the time to update / improve them.
Thank you for the feedback. 

About the qty. We discussed it and think the `qty cannot be 0` exceptions are important and not an error, These situations should be handled by the user inside his strategy (logic). This way he is aware of those situations. 

We appreciate your feedback!
