### ISSUE TITLE
Add Maker and Taker fees to exchanges

### ISSUE THREAD

**Issue by royshil** [jesse-ai/jesse#342]
**Is your feature request related to a problem? Please describe.**
Currently Jesse only allows a single fee rate in the exchanges, but in reality exchanges split fees to maker and taker, e.g. https://help.ftx.com/hc/en-us/articles/360024479432-Fees
Taker fees are usually higher (but only inflict e.g. MARKET, STOP-MARKET orders).
So smart strategies will try to utilize maker fees as much as possible, relying on LIMITs.

**Describe the solution you'd like**
I'd like an input in the settings to put in the maker and taker fees separate
And for the different order types to use the maker/taker fee accordingly.

**Describe alternatives you've considered**
There are no alternatives in Jesse, save for maybe to try to average the maker-taker fee.

**Additional context**
N/A

**Comment by saleh-mir** [comment]
My thinking was that if a strategy can be profitable with taker fees (in backtest) then it should do fine in live trading (where some might be maker fees). But because we don't support "Post only" orders, I decided not to encourage the development of strategies that depend on maker fees. 

I'm sorry about the late reply. I missed this issue. I check Discord every day though.
