### ISSUE TITLE
Add tradingview-webhook

### ISSUE THREAD

**Issue by zhihuba** [jesse-ai/jesse#392]
Describe the solution you want
Some of the metrics/robots in tradingview work well. But it is too complicated to migrate over. It's easy to automate trading with tradingview-webhook

**Comment by movy** [comment]
From my experience TradingView hooks are unreliable and have bugs, i.e. some hooks fire when they're not supposed to (due to bugs) or do NOT fire due to some tradingview infrastucture related issues. I lost quite a bit of money due to missed hooks and put some significant effort to migrate all my algos into Jesse. Jesse is not perfect either, but at least it's open sourced and most issues can be tracked down and fixed. Good luck doing this with TradingView support. 

Another issue with TradingView is impossibility to properly backtest pinescript. They keep patching loopholes that allowed to run 1000s of simulations to get best hyperparams, which is a non-issue with Jesse -- you can optimize how much you want and noone will ban your account. 

So just my 2 satoshis: it's worth spending time migrating your strategies and indicators to Jesse and abandoning TradingView altogether, instead of trying to marry them and cry over missed TV alerts later.

**Comment by zhihuba** [comment]
Thank you for the reminder. I have tried to use optuna in TradingView to find the optimal parameters. But like you said, the rate was too fast and the account was banned. Looking forward to more exchange/trading protocol support
