### ISSUE TITLE
CandleNotFoundInExchange for any timeframe, with any altcoin using Coinbase Spot

### ISSUE THREAD

**Issue by jcrowthe** [jesse-ai/jesse#442]
**Describe the bug**
When attempting to import candles from Coinbase for anything other than `BTC-USD` or `ETH-USD`, the following error message is produced:

```
Traceback (most recent call last):
  File "/jesse-docker/jesse/services/multiprocessing.py", line 20, in run
    mp.Process.run(self)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/jesse-docker/jesse/modes/import_candles_mode/__init__.py", line 116, in run
    raise CandleNotFoundInExchange(
jesse.exceptions.CandleNotFoundInExchange: No candles exists in the market for this day: 2024-04-22 
Try another start_date
```

Other iterations tried includes several different start dates and several random altcoins currently available in Coinbase Advanced. It appears like Jesse fails to import candles for all altcoins (though I have not thoroughly tested for completeness).

**To Reproduce**
1. Attempt to import candles from Coinbase Spot using any altcoin and any time period. Example altcoins tested: `LINK-USD`, `FIL-USD`, `TIA-USD`, `ADA-USD`.

**Expected behavior**
I expected candles to be imported, similar to when importing `BTC-USD` from Coinbase.

**Enviroment (please complete the following information):**
 - OS: [e.g. iOS, Windows, Ubuntu, Docker]
     - Docker
 - Version [use `pip show jesse`]
     - 0.47.3

**Comment by saleh-mir** [comment]
Very weird. I tried it myself. Please use other exchanges in the meantime.

**Comment by saleh-mir** [comment]
I was actually planning my next steps with my fellow developer. We were trying to figure out whether to implement Apex Pro or Coinbase first. It won't be in the far future. I want both of them like yesterday. So, hopefully, in the next one to three months max, we should see both of them. If you decide to become a premium user just for Coinbase, that would also push me a little towards implementing Coinbase first. Either way, some very cool features are coming soon, and Coinbase support is one of them.

As for [Apex Pro](https://jesse.trade/apex), We need it because the DYDX API is not as stable as I want it to be and Apex Pro seems to have a much better quality and liquidity and it's also a DEX so the self custody part of it is pretty cool.

**Comment by saleh-mir** [comment]
You're welcome and thank you. Yeah, keep up with strategies development. Hope you find a good one. That's really the first step which many skip
