### ISSUE TITLE
Use data.binance.vision for faster data downloading

### ISSUE THREAD

**Issue by size12** [jesse-ai/jesse#448]
**Is your feature request related to a problem? Please describe.**
Using Binance API for fetching candles is pretty slow

**Describe the solution you'd like**
Using https://data.binance.vision for fetching months of candles way faster

**Comment by saleh-mir** [comment]
I appreciate your feedback.
I hear you, but instead of that, in my todo list, I have this feature for allowing to import and export candles. When I do that, you can download from any source you like and import it. That way, we can support all sources because if I do this just for Binance, we still don't have it for other exchanges. I might also host some of them on my website and allow for downloading from there for unlimited symbols and exchanges. That's for the future. For now, I'd like to focus on the most requested features.
