### ISSUE TITLE
average_entry_price in Strategy is wrong

### ISSUE THREAD

**Issue by lightyear15** [jesse-ai/jesse#52]
Hello,
 while backtesting a long-only strategy I notice there might be something wrong in computing the ``average_entry_price``
Here it a sequence of buy order (1st one made in ``go_long``, the others in ``update_position``) and how the ``average_entry_price`` gets updated
```
buying qty: 3.3426391274712346 price: 150.44
average_entry_price: 150.44
buying 3.1774795305245025 150.33
average_entry_price: 150.33
buying 3.024307255417514 150.03
average_entry_price: 150.03
buying 2.8473431610486517 151.37
average_entry_price: 151.37
buying 2.6811195961259826 152.7
average_entry_price: 152.7
buying 2.5541417738143384 152.26
average_entry_price: 152.26
buying 2.4468974718562766 150.97
average_entry_price: 150.97
buying 2.318153649389877 151.37
average_entry_price: 151.37
buying 2.2468293065477463 148.35
average_entry_price: 148.35
buying 2.1494655325637435 147.3
average_entry_price: 147.3
buying 2.0424598613965914 147.25
average_entry_price: 147.25
buying 1.9870837092479907 143.77
average_entry_price: 143.77
```
It looks like ``average_entry_price`` always takes the last buying price.
Am I doing something wrong or is it a real bug?

**Comment by saleh-mir** [comment]
Nice catch. I'll fix it. Thank you

**Comment by saleh-mir** [comment]
I worked on this for hours today. Turns out it's harder that I expected. The easy fix is to consider `average_entry_price` as average of open orders. But I don't think that would be enough. How would that be in your use case?

**Comment by lightyear15** [comment]
For hours!!! I kinda feel sorry for having found the bug now :sweat_smile: 

Well, I'd say that average entry price is the weighted average of all the executed buy (sell) orders; and once the position is ``liquidate``d the ``average_entry_price`` should be reset.
So let's say I do in sequence:
1. in ``go_long()`` I do
```
qty = 0.5
self.buy = qty, self.price   
```
2.  in ``update_position`` I do
```
qty = 0.7
self.buy = qty, self.price
```
3.  in ``update_position`` I do
```
qty = 0.9
self.buy = qty, self.price
```

Assuming all 3 buy orders are executed at market price, I expect ``average_entry_price`` to be:

```
0.5 * marketPrice@1. + 0.7 * marketPrice@2. + 0.9 * marketPrice@3. / ( 0.5 + 0.7 + 0.9)
```
I annotated ``marketPrice@X.`` and not ``self.price@1.`` just so you know that I am aware of the fact that at the moment when jesse executes the order of type "MARKET" the market price can be different from ``self.price``
The real point of ``average_entry_price`` is the weighted average of all the entry prices times the quantities.

I am not sure how the ``average_entry_price`` should be updated when you reduce the position :thinking:

**Comment by saleh-mir** [comment]
I'm sorry for the long delay. 

Well, in your example you don't need `average_entry_price`! You could simply use `self.position.entry_price`. 

So I guess I have more time to work on `average_entry_price` in the future. The problem I found in it after digging into it, is  that, it is currently returning the average of OPEN entry orders only. So if you do:

```py
self.buy = [
    (0.5, 6),
    (0.5, 8),
]
```

`average_entry_price` gives you 7 which is expected. But if you already have an open position let's say at:
```py
self.buy = 1, 5
```

And then access in update_position do:
```py
self.buy = [
    (0.5, 6),
    (0.5, 8),
]
```

No you might expect the `average_entry_price` to be the average of all three prices weighted by their `qty`, but it's not. It's only the average of the 2 newly submitted orders. 

So since we already have `self.position.entry_price` for executed orders, maybe it makes sense to leave it as is. But still, we maybe the name of it is confusing and should point to OPEN orders. What do you think?

**Comment by lightyear15** [comment]
Thanks a lot,
``self.position.entry_price`` was the bad boy I was looking for.
I agree with you then... if ``self.position`` is resuming all info about current position, then ``self.average_entry_price`` should report only the average entry price of the last order.
I am closing the issue.
Thanks again
